### PR TITLE
Change Mathieu functions imported from GSL to their error-handling versions (fixes #78)

### LINKED ISSUE #78: Mathieu functions always return zero
The Mathieu functions provided in `types::mathieu::MathieuWorkspace` always return zero. Example:

~~~rust
use rgsl::types::mathieu::MathieuWorkspace;
use rgsl::Value;

fn main() {
    const Q: f64 = 0.8253525490491695;
    let foo = match MathieuWorkspace::mathieu_Mc(1, 0, Q, 0.5) {
        (Value::Success, res) => res.val,
        _ => panic!("Mathieu function failed"),
    };
    println!("{}", foo);
}
~~~

Output: `0`. This seems to happen for any input.

By contrast, for a roughly equivalent C program:

~~~c
#include <stdio.h>
#include "gsl/gsl_sf_mathieu.h"


int main() {
    double q = 0.8253525490491695;
    gsl_sf_result res;
    gsl_sf_mathieu_Mc_e(1, 0, q, 0.5, &res);
    printf("%f", res.val);
}
~~~

I get `0.666843`.

### PR DESCRIPTION
**Pull request by Jvanrhijn**

### CODE REVIEW

File: src/ffi/mod.rs [hunk 1]
```diff
@@ -1212,8 +1212,8 @@ extern "C" {
     pub fn gsl_sf_mathieu_alloc(n: size_t, qmax: c_double) -> *mut gsl_sf_mathieu_workspace;
     pub fn gsl_sf_mathieu_free(work: *mut gsl_sf_mathieu_workspace);
     // Mathieu functions Characteristic Values
-    pub fn gsl_sf_mathieu_a(n: c_int, q: c_double, result: *mut gsl_sf_result) -> c_int;
```
Comment (GuillaumeGomez) [inline src/ffi/mod.rs:1215]: Could please add the non-`_e` equivalent too please?

Comment (GuillaumeGomez) [reply src/ffi/mod.rs:1215]: Hum actually nevermind. I'll do it once this is merged.

**Comment by GuillaumeGomez** [comment]
Thanks a lot! I add the non-`_e` equivalents then I make a new release.
